In [78]:
import pandas as pd
import numpy as np

## Load Datasets

In [79]:
# Load datasets
properties = pd.read_csv('properties.csv')
customers = pd.read_csv('customers.csv')

In [80]:
properties.head()

,Unnamed: 0,﻿id,building,date_sale,type,property#,area,price,status,customerid
0,0,1030,1,11/1/2005,Apartment,30,743.09,"$246,172.68",Sold,C0028
1,1,1029,1,10/1/2005,Apartment,29,756.21,"$246,331.90",Sold,C0027
2,2,2002,2,7/1/2007,Apartment,2,587.28,"$209,280.91",Sold,C0112
3,3,2031,2,12/1/2007,Apartment,31,1604.75,"$452,667.01",Sold,C0160
4,4,1049,1,11/1/2004,Apartment,49,1375.45,"$467,083.31",Sold,C0014

In [81]:
customers.head()

,Unnamed: 0,﻿customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,0,C0110,Individual,Kareem,Liu,5/11/1968,F,USA,California,Home,4,Yes,Website
1,1,C0010,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,2,C0132,Individual,Kale,Gay,4/7/1959,M,USA,California,Home,4,Yes,Agency
3,3,C0137,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,4,C0174,Company,Marleez,Co,NaN,NaN,USA,California,Investment,5,No,Website

## Data Preprocessing of 'properties' dataset

In [82]:
# Drop the 'Unnamed: 0' column
properties = properties.drop('Unnamed: 0', axis=1)

# Print the updated properties DataFrame
properties.head()

,﻿id,building,date_sale,type,property#,area,price,status,customerid
0,1030,1,11/1/2005,Apartment,30,743.09,"$246,172.68",Sold,C0028
1,1029,1,10/1/2005,Apartment,29,756.21,"$246,331.90",Sold,C0027
2,2002,2,7/1/2007,Apartment,2,587.28,"$209,280.91",Sold,C0112
3,2031,2,12/1/2007,Apartment,31,1604.75,"$452,667.01",Sold,C0160
4,1049,1,11/1/2004,Apartment,49,1375.45,"$467,083.31",Sold,C0014

In [83]:
# Descriptive statistics
properties_stats = properties.describe(include='all')
print(properties_stats)

                ﻿id    building date_sale       type   property#         area  \
count    267.000000  267.000000       267        267  267.000000   267.000000
unique          NaN         NaN        44          2         NaN          NaN
top             NaN         NaN     #NUM!  Apartment         NaN          NaN
freq            NaN         NaN        72        259         NaN          NaN
mean    2975.142322    2.947566       NaN        NaN   27.580524   936.221311
std     1392.197474    1.391794       NaN        NaN   15.361437   284.894858
min     1002.000000    1.000000       NaN        NaN    1.000000   410.710000
25%     2015.500000    2.000000       NaN        NaN   14.500000   756.210000
50%     3024.000000    3.000000       NaN        NaN   28.000000   798.280000
75%     4031.500000    4.000000       NaN        NaN   40.000000  1121.950000
max     5052.000000    5.000000       NaN        NaN   59.000000  1942.500000

               price  status customerid
count            267     267        195
unique           266       2        162
top     $460,001.26    Sold      C0174
freq               2     195          9
mean             NaN     NaN        NaN
std              NaN     NaN        NaN
min              NaN     NaN        NaN
25%              NaN     NaN        NaN
50%              NaN     NaN        NaN
75%              NaN     NaN        NaN
max              NaN     NaN        NaN

In [84]:
# Check for missing values
properties_missing = properties.isnull().sum()
print(properties_missing)

﻿id            0
building       0
date_sale      0
type           0
property#      0
area           0
price          0
status         0
customerid    72
dtype: int64

In [85]:
# Display the rows with NaN values in the 'customerid' column
nan_customerid_rows = properties[pd.isna(properties['customerid'])]
print(nan_customerid_rows)

      ﻿id  building date_sale       type  property#     area         price  \
178  5052         5     #NUM!  Apartment         52  1769.48  $532,877.38
196  1002         1     #NUM!  Apartment          2  1238.58  $400,865.92
197  1003         1     #NUM!     Office          3   713.71  $217,787.71
198  1008         1     #NUM!  Apartment          8   763.21  $219,630.90
199  1019         1     #NUM!  Apartment         19   798.50  $244,624.87
..    ...       ...       ...        ...        ...      ...           ...
262  5044         5     #NUM!  Apartment         44  1238.58  $322,610.74
263  5047         5     #NUM!  Apartment         47   794.52  $279,191.26
264  5048         5     #NUM!  Apartment         48  1013.27  $287,996.53
265  5050         5     #NUM!  Apartment         50  1074.71  $365,868.78
266  5051         5     #NUM!  Apartment         51   789.25  $199,216.40

    status customerid
178      -        NaN
196      -        NaN
197      -        NaN
198      -        NaN
199      -        NaN
..     ...        ...
262      -        NaN
263      -        NaN
264      -        NaN
265      -        NaN
266      -        NaN

[72 rows x 9 columns]

In [86]:
properties['date_sale'].unique()

array(['11/1/2005', '10/1/2005', '7/1/2007', '12/1/2007', '11/1/2004',
       '9/1/2007', '1/1/2008', '6/1/2006', '3/1/2006', '10/1/2004',
       '8/1/2006', '10/1/2007', '11/1/2006', '4/1/2007', '10/1/2006',
       '12/1/2006', '3/1/2005', '3/1/2007', '9/1/2006', '1/1/2007',
       '5/1/2007', '7/1/2006', '5/1/2008', '11/1/2007', '1/1/2005',
       '8/1/2007', '6/1/2005', '2/1/2007', '6/1/2007', '2/1/2005',
       '8/1/2004', '12/1/2008', '5/1/2010', '4/1/2006', '8/1/2005',
       '6/1/2004', '12/1/2005', '3/1/2004', '2/1/2006', '4/1/2005',
       '5/1/2006', '#NUM!', '9/1/2005', '7/1/2005'], dtype=object)

The missing values of the 'date_sale' are due to unsold properties. We will substitute them with NA values.

In [87]:
# A convenient way to implement this substitution is using the 'np.where' function.
properties['date_sale'] = np.where(properties['date_sale']=='#NUM!', pd.NA, properties['date_sale'])

# Rechecking the unique entries
properties['date_sale'].unique()

array(['11/1/2005', '10/1/2005', '7/1/2007', '12/1/2007', '11/1/2004',
       '9/1/2007', '1/1/2008', '6/1/2006', '3/1/2006', '10/1/2004',
       '8/1/2006', '10/1/2007', '11/1/2006', '4/1/2007', '10/1/2006',
       '12/1/2006', '3/1/2005', '3/1/2007', '9/1/2006', '1/1/2007',
       '5/1/2007', '7/1/2006', '5/1/2008', '11/1/2007', '1/1/2005',
       '8/1/2007', '6/1/2005', '2/1/2007', '6/1/2007', '2/1/2005',
       '8/1/2004', '12/1/2008', '5/1/2010', '4/1/2006', '8/1/2005',
       '6/1/2004', '12/1/2005', '3/1/2004', '2/1/2006', '4/1/2005',
       '5/1/2006', <NA>, '9/1/2005', '7/1/2005'], dtype=object)

In [88]:
# Convert date_sale to datetime
properties['date_sale'] = pd.to_datetime(properties['date_sale'])
# Let's review the changes.
properties['date_sale']

0     2005-11-01
1     2005-10-01
2     2007-07-01
3     2007-12-01
4     2004-11-01
         ...
262          NaT
263          NaT
264          NaT
265          NaT
266          NaT
Name: date_sale, Length: 267, dtype: datetime64[ns]

In [89]:
# Datatypes
print(properties.dtypes)

﻿id                    int64
building               int64
date_sale     datetime64[ns]
type                  object
property#              int64
area                 float64
price                 object
status                object
customerid            object
dtype: object

In [90]:
# Column names
print(properties.columns)

Index(['﻿id', 'building', 'date_sale', 'type', 'property#', 'area', 'price',
       'status', 'customerid'],
      dtype='object')

In [91]:
# Rename 'property#' column to 'property_number'
properties = properties.rename(columns={'property#': 'property_number'})

In [92]:
# Convert 'price' column to float
properties['price'] = properties['price'].str.replace('$', '').str.replace(',', '').astype('float64')
properties.price.dtype

<ipython-input-92-8d757b6b6d4a>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  properties['price'] = properties['price'].str.replace('$', '').str.replace(',', '').astype('float64')

dtype('float64')

In [93]:
# Check unique values in 'status' column of properties dataset after stripping it
properties.status.unique()

array([' Sold ', '-'], dtype=object)

In [94]:
# Map 'status' column: 1 for 'Sold', 0 for '-'
properties['status'] = properties['status'].str.strip().replace({'Sold': 1, '-': 0})

In [95]:
# We will also rename the 'status' column to 'sold' for better reference
properties = properties.rename(columns={'status': 'sold'})

In [96]:
# Check unique values in 'type' column of properties dataset
properties.type.unique()

array(['Apartment', 'Office'], dtype=object)

In [97]:
# Map 'type' column in zero for Apartment and one for Office
properties['type'] = properties['type'].map({'Apartment': 0, 'Office': 1})

In [98]:
# Rename '﻿id' column to 'id' without the leading special character
properties.rename(columns={'﻿id': 'id'}, inplace=True)

In [99]:
properties.head()

,id,building,date_sale,type,property_number,area,price,sold,customerid
0,1030,1,2005-11-01,0,30,743.09,246172.68,1,C0028
1,1029,1,2005-10-01,0,29,756.21,246331.90,1,C0027
2,2002,2,2007-07-01,0,2,587.28,209280.91,1,C0112
3,2031,2,2007-12-01,0,31,1604.75,452667.01,1,C0160
4,1049,1,2004-11-01,0,49,1375.45,467083.31,1,C0014

In [100]:
properties.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 267 entries, 0 to 266
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               267 non-null    int64
 1   building         267 non-null    int64
 2   date_sale        195 non-null    datetime64[ns]
 3   type             267 non-null    int64
 4   property_number  267 non-null    int64
 5   area             267 non-null    float64
 6   price            267 non-null    float64
 7   sold             267 non-null    int64
 8   customerid       195 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(5), object(1)
memory usage: 18.9+ KB

## Data Preprocessing of 'customers' dataset

In [101]:
# Drop the 'Unnamed: 0' column
customers = customers.drop('Unnamed: 0', axis=1)
# Print the updated customers DataFrame
customers.head()

,﻿customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,C0110,Individual,Kareem,Liu,5/11/1968,F,USA,California,Home,4,Yes,Website
1,C0010,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0132,Individual,Kale,Gay,4/7/1959,M,USA,California,Home,4,Yes,Agency
3,C0137,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0174,Company,Marleez,Co,NaN,NaN,USA,California,Investment,5,No,Website

In [102]:
# Rename '﻿customerid' column to 'customerid' without the leading special character
customers.rename(columns={'﻿customerid': 'customerid'}, inplace=True)

In [103]:
# Descriptive statistics of the customers dataset
customers_stats = customers.describe(include="all")
print(customers_stats)

       customerid      entity  name surname birth_date  sex country  \
count         162         162   162     162        155  155     162
unique        162           2   159     156        151    2       9
top         C0110  Individual  Jack      Co  9/14/1966    M     USA
freq            1         155     2       7          2   87     146
mean          NaN         NaN   NaN     NaN        NaN  NaN     NaN
std           NaN         NaN   NaN     NaN        NaN  NaN     NaN
min           NaN         NaN   NaN     NaN        NaN  NaN     NaN
25%           NaN         NaN   NaN     NaN        NaN  NaN     NaN
50%           NaN         NaN   NaN     NaN        NaN  NaN     NaN
75%           NaN         NaN   NaN     NaN        NaN  NaN     NaN
max           NaN         NaN   NaN     NaN        NaN  NaN     NaN

             state purpose  deal_satisfaction mortgage   source
count          154     162         162.000000      162      162
unique           9       2                NaN        2        3
top     California    Home                NaN       No  Website
freq           100     112                NaN      102       93
mean           NaN     NaN           3.456790      NaN      NaN
std            NaN     NaN           1.333276      NaN      NaN
min            NaN     NaN           1.000000      NaN      NaN
25%            NaN     NaN           3.000000      NaN      NaN
50%            NaN     NaN           4.000000      NaN      NaN
75%            NaN     NaN           5.000000      NaN      NaN
max            NaN     NaN           5.000000      NaN      NaN

In [104]:
# Datatypes
print(customers.dtypes)

customerid           object
entity               object
name                 object
surname              object
birth_date           object
sex                  object
country              object
state                object
purpose              object
deal_satisfaction     int64
mortgage             object
source               object
dtype: object

In [105]:
# Column names
print(customers.columns)

Index(['customerid', 'entity', 'name', 'surname', 'birth_date', 'sex',
       'country', 'state', 'purpose', 'deal_satisfaction', 'mortgage',
       'source'],
      dtype='object')

In [106]:
# Check for missing values
customers_missing = customers.isnull().sum()
print(customers_missing)

customerid           0
entity               0
name                 0
surname              0
birth_date           7
sex                  7
country              0
state                8
purpose              0
deal_satisfaction    0
mortgage             0
source               0
dtype: int64

In [107]:
# Check unique values in 'entity' column of customers dataset
customers.entity.unique()

array(['Individual', 'Company'], dtype=object)

In [108]:
# Map 'entity' column in zero for individuals and one for companies
customers['entity'] = customers['entity'].map({'Individual': 0, 'Company': 1})

In [109]:
customers['entity'].value_counts()

0    155
1      7
Name: entity, dtype: int64

We see 155 individuals and 7 companies.

In [110]:
customers['source'].unique()

array(['Website', 'Agency', 'Client'], dtype=object)

In [111]:
# Map 'source' column in zero for Home and one for Investment
customers['source'] = customers['source'].map({'Website': 0, 'Agency': 1, 'Client':3})

In [112]:
customers['purpose'].unique()

array(['Home', 'Investment'], dtype=object)

In [113]:
# Map 'purpose' column in zero for Home and one for Investment
customers['purpose'] = customers['purpose'].map({'Home': 0, 'Investment': 1})

In [114]:
customers['mortgage'].unique()

array(['Yes', 'No'], dtype=object)

In [115]:
# Map 'mortgage' column in zero for No and one for Yes
customers['mortgage'] = customers['mortgage'].map({'No': 0, 'Yes': 1})

In [116]:
customers['sex'].unique()# Map 'sex' column in zero for Male and one for Female

array(['F', 'M', nan], dtype=object)

In [117]:
# Display the rows with NaN values in the 'sex' column
nan_sex_rows = customers[pd.isna(customers['sex'])]
print(nan_sex_rows)

    customerid  entity         name surname birth_date  sex country  \
4        C0174       1      Marleez      Co        NaN  NaN    USA
11       C0055       1        Kylax      Co        NaN  NaN     USA
13       C0121       1       Esther      Co        NaN  NaN     USA
53       C0012       1  Bridger CAL      Co        NaN  NaN     USA
57       C0029       1       Kenyon      Co        NaN  NaN     USA
127      C0025       1       Abdiel      Co        NaN  NaN     USA
154      C0001       1         Kamd      Co        NaN  NaN     USA

          state  purpose  deal_satisfaction  mortgage  source
4    California        1                  5         0       0
11   California        1                  5         0       0
13   California        0                  3         1       0
53       Nevada        1                  5         0       0
57   California        1                  1         1       0
127      Nevada        1                  5         1       0
154  California        1                  5         0       1

We notice 7 rows with NaN values in birth_date and sex that correspond to the 7 companies we found above, so this is natural not to have birth_date and sex.

In [118]:
# Identify and update 'sex' column for companies
company_rows = customers['entity'] == 1
customers.loc[company_rows, 'sex'] = 'Company'

# Display the DataFrame after updating 'sex' for companies
print(customers)

    customerid  entity     name     surname  birth_date      sex country  \
0        C0110       0   Kareem         Liu   5/11/1968        F     USA
1        C0010       0  Trystan     Oconnor  11/26/1962        M     USA
2        C0132       0     Kale         Gay    4/7/1959        M     USA
3        C0137       0  Russell       Gross  11/25/1959        M     USA
4        C0174       1  Marleez          Co         NaN  Company    USA
..         ...     ...      ...         ...         ...      ...     ...
157      C0170       0     Emmy       Singh   12/3/1979        F     USA
158      C0138       0    Colin      Campos   4/14/1942        M     USA
159      C0113       0     Anya  Stephenson   6/11/1959        F     USA
160      C0147       0   Parker       Poole  11/10/1951        M     USA
161      C0133       0     Ivan      Bright   9/15/1953        M     USA

          state  purpose  deal_satisfaction  mortgage  source
0    California        0                  4         1       0
1    California        0                  1         0       0
2    California        0                  4         1       1
3    California        0                  5         0       0
4    California        1                  5         0       0
..          ...      ...                ...       ...     ...
157    Virginia        1                  3         1       1
158  California        0                  3         0       0
159  California        0                  4         0       0
160  California        0                  5         0       0
161  California        0                  4         0       0

[162 rows x 12 columns]

In [119]:
# Map 'sex' column in zero for Male and one for Female
customers['sex'] = customers['sex'].map({'M': 0, 'F': 1, 'Company':3})

In [120]:
# Convert 'birth_date' column to datetime
customers['birth_date'] = pd.to_datetime(customers['birth_date'])

In [121]:
customers['country'] = customers['country'].str.strip()

In [122]:
customers['country'].unique()

array(['USA', 'Canada', 'Germany', 'Belgium', 'Mexico', 'Russia', 'UK',
       'Denmark'], dtype=object)

In [123]:
customers['state'].unique()

array(['California', nan, 'Oregon', 'Arizona', 'Nevada', 'Colorado',
       'Utah', 'Virginia', 'Wyoming', 'Kansas'], dtype=object)

In [124]:
# Display the rows with NaN values in the 'state' column
nan_state_rows = customers[pd.isna(customers['state'])]
print(nan_state_rows)

    customerid  entity        name      surname birth_date  sex  country  \
6        C0079       0      Xavier     Faulkner 1947-05-24    0   Canada
33       C0015       0      Lauryn      Patrick 1969-10-30    1  Belgium
34       C0084       0       Diego       Mendez 1965-05-12    0   Mexico
38       C0070       0  Aleksandra     Karenina 1967-06-13    1   Russia
72       C0047       0   Alejandra        Greer 1965-01-11    1  Denmark
97       C0059       0       Elena      Petrova 1949-06-22    1   Russia
133      C0021       0      Kaylin   Villarreal 1932-06-13    1   Russia
148      C0063       0       Piotr  Aleksandrov 1955-12-02    0   Russia

    state  purpose  deal_satisfaction  mortgage  source
6     NaN        1                  5         0       0
33    NaN        0                  2         0       1
34    NaN        0                  3         0       1
38    NaN        0                  1         0       1
72    NaN        1                  1         0       1
97    NaN        0                  3         1       1
133   NaN        1                  3         0       0
148   NaN        1                  3         0       1

In [125]:
# Fill NaN values in 'state' with corresponding 'country' values
customers['state'].fillna(customers['country'], inplace=True)

# Display the updated DataFrame
print(customers)

    customerid  entity     name     surname birth_date  sex country  \
0        C0110       0   Kareem         Liu 1968-05-11    1     USA
1        C0010       0  Trystan     Oconnor 1962-11-26    0     USA
2        C0132       0     Kale         Gay 1959-04-07    0     USA
3        C0137       0  Russell       Gross 1959-11-25    0     USA
4        C0174       1  Marleez          Co        NaT    3     USA
..         ...     ...      ...         ...        ...  ...     ...
157      C0170       0     Emmy       Singh 1979-12-03    1     USA
158      C0138       0    Colin      Campos 1942-04-14    0     USA
159      C0113       0     Anya  Stephenson 1959-06-11    1     USA
160      C0147       0   Parker       Poole 1951-11-10    0     USA
161      C0133       0     Ivan      Bright 1953-09-15    0     USA

          state  purpose  deal_satisfaction  mortgage  source
0    California        0                  4         1       0
1    California        0                  1         0       0
2    California        0                  4         1       1
3    California        0                  5         0       0
4    California        1                  5         0       0
..          ...      ...                ...       ...     ...
157    Virginia        1                  3         1       1
158  California        0                  3         0       0
159  California        0                  4         0       0
160  California        0                  5         0       0
161  California        0                  4         0       0

[162 rows x 12 columns]

In [126]:
# Merge after removing spaces in 'customerid' column
pd.merge(properties, customers, on='customerid', how='left')

,id,building,date_sale,type,property_number,area,price,sold,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,1030,1,2005-11-01,0,30,743.09,246172.68,1,C0028,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1029,1,2005-10-01,0,29,756.21,246331.90,1,C0027,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002,2,2007-07-01,0,2,587.28,209280.91,1,C0112,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2031,2,2007-12-01,0,31,1604.75,452667.01,1,C0160,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1049,1,2004-11-01,0,49,1375.45,467083.31,1,C0014,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,5044,5,NaT,0,44,1238.58,322610.74,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,5047,5,NaT,0,47,794.52,279191.26,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,5048,5,NaT,0,48,1013.27,287996.53,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,5050,5,NaT,0,50,1074.71,365868.78,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,5051,5,NaT,0,51,789.25,199216.40,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We opted for a left join, retaining all rows from the 'properties' dataframe and appending matching rows from the 'customers' dataframe. There's no match, the resultant dataframe has 'NA' for the corresponding 'customers' dataframe columns. The merge did not work as intended. There probably is a problem with the key, so we will investigate further.

In [127]:
properties.customerid.unique()

array([' C0028 ', ' C0027 ', ' C0112 ', ' C0160 ', ' C0014 ', ' C0125 ',
       ' C0166 ', ' C0034 ', ' C0170 ', ' C0009 ', ' C0041 ', ' C0057 ',
       ' C0061 ', ' C0089 ', ' C0159 ', ' C0171 ', ' C0042 ', ' C0093 ',
       ' C0051 ', ' C0064 ', ' C0128 ', ' C0019 ', ' C0037 ', ' C0127 ',
       ' C0018 ', ' C0040 ', ' C0080 ', ' C0083 ', ' C0085 ', ' C0091 ',
       ' C0007 ', ' C0048 ', ' C0065 ', ' C0096 ', ' C0164 ', ' C0038 ',
       ' C0087 ', ' C0142 ', ' C0015 ', ' C0122 ', ' C0017 ', ' C0020 ',
       ' C0086 ', ' C0150 ', ' C0156 ', ' C0169 ', ' C0022 ', ' C0072 ',
       ' C0136 ', ' C0149 ', ' C0011 ', ' C0073 ', ' C0110 ', ' C0111 ',
       ' C0123 ', ' C0070 ', ' C0075 ', ' C0076 ', ' C0105 ', ' C0135 ',
       ' C0153 ', ' C0047 ', ' C0060 ', ' C0066 ', ' C0068 ', ' C0090 ',
       ' C0095 ', ' C0151 ', ' C0162 ', ' C0010 ', ' C0054 ', ' C0056 ',
       ' C0081 ', ' C0084 ', ' C0016 ', ' C0035 ', ' C0062 ', ' C0099 ',
       ' C0114 ', ' C0006 ', ' C0053 ', ' C0069 ', ' C0077 ', ' C0168 ',
       ' C0058 ', ' C0107 ', ' C0131 ', ' C0144 ', ' C0098 ', ' C0130 ',
       ' C0141 ', ' C0067 ', ' C0082 ', ' C0113 ', ' C0132 ', ' C0137 ',
       ' C0155 ', ' C0163 ', ' C0039 ', ' C0071 ', ' C0101 ', ' C0146 ',
       ' C0052 ', ' C0063 ', ' C0088 ', ' C0094 ', ' C0165 ', ' C0044 ',
       ' C0157 ', ' C0118 ', ' C0119 ', ' C0033 ', ' C0100 ', ' C0133 ',
       ' C0175 ', ' C0008 ', ' C0023 ', ' C0108 ', ' C0109 ', ' C0145 ',
       ' C0003 ', ' C0004 ', ' C0024 ', ' C0030 ', ' C0147 ', ' C0002 ',
       ' C0031 ', ' C0059 ', ' C0140 ', ' C0043 ', ' C0078 ', ' C0124 ',
       ' C0049 ', ' C0079 ', ' C0013 ', ' C0139 ', ' C0154 ', ' C0045 ',
       ' C0134 ', ' C0138 ', ' C0158 ', ' C0036 ', ' C0074 ', ' C0120 ',
       ' C0005 ', ' C0032 ', ' C0126 ', ' C0106 ', ' C0115 ', ' C0129 ',
       ' C0103 ', ' C0021 ', ' C0148 ', ' C0172 ', ' C0104 ', nan,
       ' C0001 ', ' C0012 ', ' C0025 ', ' C0029 ', ' C0055 ', ' C0121 ',
       ' C0174 '], dtype=object)

In [128]:
customers.customerid.unique()

array(['C0110', 'C0010', 'C0132', 'C0137', 'C0174', 'C0088', 'C0079',
       'C0149', 'C0064', 'C0068', 'C0006', 'C0055', 'C0016', 'C0121',
       'C0074', 'C0032', 'C0093', 'C0076', 'C0165', 'C0153', 'C0129',
       'C0162', 'C0071', 'C0069', 'C0005', 'C0144', 'C0020', 'C0101',
       'C0128', 'C0033', 'C0171', 'C0095', 'C0123', 'C0015', 'C0084',
       'C0019', 'C0053', 'C0080', 'C0070', 'C0051', 'C0022', 'C0127',
       'C0081', 'C0104', 'C0073', 'C0168', 'C0169', 'C0039', 'C0086',
       'C0036', 'C0045', 'C0105', 'C0119', 'C0012', 'C0065', 'C0054',
       'C0172', 'C0029', 'C0098', 'C0142', 'C0135', 'C0037', 'C0134',
       'C0091', 'C0018', 'C0085', 'C0061', 'C0066', 'C0156', 'C0043',
       'C0112', 'C0145', 'C0047', 'C0082', 'C0007', 'C0052', 'C0041',
       'C0004', 'C0118', 'C0030', 'C0154', 'C0125', 'C0115', 'C0078',
       'C0151', 'C0111', 'C0014', 'C0103', 'C0024', 'C0166', 'C0067',
       'C0122', 'C0107', 'C0003', 'C0099', 'C0160', 'C0013', 'C0059',
       'C0120', 'C0150', 'C0140', 'C0002', 'C0096', 'C0159', 'C0163',
       'C0100', 'C0155', 'C0049', 'C0148', 'C0146', 'C0034', 'C0141',
       'C0008', 'C0131', 'C0089', 'C0157', 'C0114', 'C0124', 'C0158',
       'C0175', 'C0023', 'C0164', 'C0058', 'C0062', 'C0042', 'C0048',
       'C0083', 'C0025', 'C0087', 'C0094', 'C0038', 'C0011', 'C0139',
       'C0021', 'C0106', 'C0040', 'C0035', 'C0126', 'C0136', 'C0109',
       'C0028', 'C0057', 'C0130', 'C0044', 'C0056', 'C0077', 'C0031',
       'C0072', 'C0063', 'C0017', 'C0009', 'C0075', 'C0027', 'C0060',
       'C0001', 'C0090', 'C0108', 'C0170', 'C0138', 'C0113', 'C0147',
       'C0133'], dtype=object)

In [129]:
# Let's trim the unnecessary white space from 'customerid' in the properties dataframe.
properties['customerid'] = properties['customerid'].str.strip()

# We'll trim the 'customerid' column to maintain consistency
customers['customerid'] = customers['customerid'].str.strip()

In [130]:
# To ensure a successful merge, we must ensure that 'customerid' in the customers table has only unique values.
# Here's the total count of entries in the customers dataframe.
customers.count()

customerid           162
entity               162
name                 162
surname              162
birth_date           155
sex                  162
country              162
state                162
purpose              162
deal_satisfaction    162
mortgage             162
source               162
dtype: int64

In [131]:
# Count of unique entries in the 'customerid' column of the properties dataframe.
properties['customerid'].nunique()

162

In [132]:
# We've observed that there's an empty space in 'customerid' in the 'properties' dataframe.
# Let's replace it with 'NA'. This corresponds to properties that are not yet purchased.
properties['customerid'] = np.where(properties['customerid']=='', pd.NA, properties['customerid'])

In [133]:
# Let's rename our merged dataframe to 'real_estate_data' for clarity.
real_estate_data = pd.merge(properties, customers, on='customerid', how='left')

In [134]:
# Our data preprocessing step has been successful. Let's take a look at the head of our processed dataframe.
real_estate_data.head()

,id,building,date_sale,type,property_number,area,price,sold,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,1030,1,2005-11-01,0,30,743.09,246172.68,1,C0028,0.0,Madalyn,Mercer,1986-06-21,1.0,USA,California,0.0,5.0,0.0,0.0
1,1029,1,2005-10-01,0,29,756.21,246331.90,1,C0027,0.0,Lara,Carrillo,1983-02-24,1.0,USA,California,0.0,5.0,0.0,0.0
2,2002,2,2007-07-01,0,2,587.28,209280.91,1,C0112,0.0,Donavan,Flowers,1985-12-27,0.0,USA,California,0.0,1.0,1.0,3.0
3,2031,2,2007-12-01,0,31,1604.75,452667.01,1,C0160,0.0,Darien,Dorsey,1985-12-27,0.0,USA,California,1.0,3.0,1.0,0.0
4,1049,1,2004-11-01,0,49,1375.45,467083.31,1,C0014,0.0,Alessandra,Perry,1979-05-15,1.0,USA,California,0.0,4.0,0.0,1.0

In [135]:
real_estate_data.tail()

,id,building,date_sale,type,property_number,area,price,sold,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
262,5044,5,NaT,0,44,1238.58,322610.74,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,5047,5,NaT,0,47,794.52,279191.26,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,5048,5,NaT,0,48,1013.27,287996.53,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,5050,5,NaT,0,50,1074.71,365868.78,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,5051,5,NaT,0,51,789.25,199216.40,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
# Given the numerous NaN values in our dataset,
# it would be beneficial to replace them with pandas' native representation for missing values.
real_estate_data.fillna(pd.NA)

,id,building,date_sale,type,property_number,area,price,sold,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,1030,1,2005-11-01,0,30,743.09,246172.68,1,C0028,0.0,Madalyn,Mercer,1986-06-21,1.0,USA,California,0.0,5.0,0.0,0.0
1,1029,1,2005-10-01,0,29,756.21,246331.90,1,C0027,0.0,Lara,Carrillo,1983-02-24,1.0,USA,California,0.0,5.0,0.0,0.0
2,2002,2,2007-07-01,0,2,587.28,209280.91,1,C0112,0.0,Donavan,Flowers,1985-12-27,0.0,USA,California,0.0,1.0,1.0,3.0
3,2031,2,2007-12-01,0,31,1604.75,452667.01,1,C0160,0.0,Darien,Dorsey,1985-12-27,0.0,USA,California,1.0,3.0,1.0,0.0
4,1049,1,2004-11-01,0,49,1375.45,467083.31,1,C0014,0.0,Alessandra,Perry,1979-05-15,1.0,USA,California,0.0,4.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,5044,5,NaT,0,44,1238.58,322610.74,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,5047,5,NaT,0,47,794.52,279191.26,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,5048,5,NaT,0,48,1013.27,287996.53,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,5050,5,NaT,0,50,1074.71,365868.78,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,5051,5,NaT,0,51,789.25,199216.40,0,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
real_estate_data.dtypes

id                            int64
building                      int64
date_sale            datetime64[ns]
type                          int64
property_number               int64
area                        float64
price                       float64
sold                          int64
customerid                   object
entity                      float64
name                         object
surname                      object
birth_date           datetime64[ns]
sex                         float64
country                      object
state                        object
purpose                     float64
deal_satisfaction           float64
mortgage                    float64
source                      float64
dtype: object

## Statistics

In [138]:
# We'll assign the cleaned and preprocessed data to a new variable 'data'.
data = real_estate_data.copy()

In [139]:
# Let's inspect the first few rows of our processed data.
data.head()

,id,building,date_sale,type,property_number,area,price,sold,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
0,1030,1,2005-11-01,0,30,743.09,246172.68,1,C0028,0.0,Madalyn,Mercer,1986-06-21,1.0,USA,California,0.0,5.0,0.0,0.0
1,1029,1,2005-10-01,0,29,756.21,246331.90,1,C0027,0.0,Lara,Carrillo,1983-02-24,1.0,USA,California,0.0,5.0,0.0,0.0
2,2002,2,2007-07-01,0,2,587.28,209280.91,1,C0112,0.0,Donavan,Flowers,1985-12-27,0.0,USA,California,0.0,1.0,1.0,3.0
3,2031,2,2007-12-01,0,31,1604.75,452667.01,1,C0160,0.0,Darien,Dorsey,1985-12-27,0.0,USA,California,1.0,3.0,1.0,0.0
4,1049,1,2004-11-01,0,49,1375.45,467083.31,1,C0014,0.0,Alessandra,Perry,1979-05-15,1.0,USA,California,0.0,4.0,0.0,1.0

In [140]:
# As we're transitioning into the statistical analysis phase, running descriptive statistics would be particularly helpful.
data.describe(include="all")

<ipython-input-140-635d245713ef>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  data.describe(include="all")
<ipython-input-140-635d245713ef>:2: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  data.describe(include="all")

,id,building,date_sale,type,property_number,area,price,sold,customerid,entity,name,surname,birth_date,sex,country,state,purpose,deal_satisfaction,mortgage,source
count,267.000000,267.000000,195,267.000000,267.000000,267.000000,267.000000,267.000000,195,195.000000,195,195,178,195.000000,195,195,195.000000,195.000000,195.000000,195.000000
unique,NaN,NaN,43,NaN,NaN,NaN,NaN,NaN,162,NaN,159,156,151,NaN,8,14,NaN,NaN,NaN,NaN
top,NaN,NaN,2007-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,C0174,NaN,Marleez,Co,1947-05-24 00:00:00,NaN,USA,California,NaN,NaN,NaN,NaN
freq,NaN,NaN,17,NaN,NaN,NaN,NaN,NaN,9,NaN,9,17,7,NaN,177,120,NaN,NaN,NaN,NaN
first,NaN,NaN,2004-03-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1931-02-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,2010-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1986-06-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2975.142322,2.947566,NaN,0.029963,27.580524,936.221311,281171.901386,0.730337,NaN,0.087179,NaN,NaN,NaN,0.620513,NaN,NaN,0.389744,3.600000,0.317949,0.564103
std,1392.197474,1.391794,NaN,0.170804,15.361437,284.894858,89119.121005,0.444618,NaN,0.282824,NaN,NaN,NaN,0.873192,NaN,NaN,0.488947,1.340872,0.466878,0.879165
min,1002.000000,1.000000,NaN,0.000000,1.000000,410.710000,117564.070000,0.000000,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,1.000000,0.000000,0.000000
25%,2015.500000,2.000000,NaN,0.000000,14.500000,756.210000,217553.055000,0.000000,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,3.000000,0.000000,0.000000
50%,3024.000000,3.000000,NaN,0.000000,28.000000,798.280000,249075.660000,1.000000,NaN,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,4.000000,0.000000,0.000000
75%,4031.500000,4.000000,NaN,0.000000,40.000000,1121.950000,326964.855000,1.000000,NaN,0.000000,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,5.000000,1.000000,1.000000
max,5052.000000,5.000000,NaN,1.000000,59.000000,1942.500000,538271.740000,1.000000,NaN,1.000000,NaN,NaN,NaN,3.000000,NaN,NaN,1.000000,5.000000,1.000000,3.000000

## Breakdowns by Building

In [141]:
# Let's identify the unique buildings in our dataset.
data['building'].unique()

array([1, 2, 3, 4, 5])

In [142]:
# Let's experiment with grouping the data by 'building'.
data.groupby('building').sum()

<ipython-input-142-b0b3d83a8f35>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data.groupby('building').sum()

,id,type,property_number,area,price,sold,entity,sex,purpose,deal_satisfaction,mortgage,source
building,,,,,,,,,,,,
1,53292,8,1293,48258.02,14307448.61,46,15.0,58.0,19.0,167.0,14.0,8.0
2,115650,0,1650,53801.84,16339725.35,54,2.0,26.0,20.0,190.0,18.0,45.0
3,190872,0,1872,58454.70,17668429.10,53,0.0,17.0,24.0,189.0,15.0,43.0
4,173132,0,1132,41913.00,12480299.17,23,0.0,13.0,3.0,89.0,9.0,7.0
5,261417,0,1417,47543.53,14276995.44,19,0.0,7.0,10.0,67.0,6.0,7.0

In [143]:
# Let's commence with deriving total counts per building.
columns_of_interest = ['building', 'sold','mortgage']

# Now we will create a new variable to hold the total counts grouped by building.
totals_by_building = data[columns_of_interest].groupby("building").sum()
totals_by_building

          sold  mortgage
building
1           46      14.0
2           54      18.0
3           53      15.0
4           23       9.0
5           19       6.0

In [69]:
columns_of_interest = ['building', 'area', 'price', 'deal_satisfaction']

# Let's now create a new variable to hold the average values grouped by building.
averages_by_building = data[columns_of_interest].groupby("building").mean()
averages_by_building

                area          price  deal_satisfaction
building
1         928.038846  275143.242500           3.630435
2         943.891930  286661.848246           3.518519
3         927.852381  280451.255556           3.566038
4         974.720930  290239.515581           3.869565
5         914.298654  274557.604615           3.526316

## Breakdowns by country and state

In [144]:
columns_of_interest = ['country', 'sold','mortgage']
totals_by_country = data[columns_of_interest].groupby("country").sum()
totals_by_country.sort_values('sold', ascending=False)

         sold  mortgage
country
USA       177      61.0
Canada      7       0.0
Russia      4       1.0
Belgium     2       0.0
UK          2       0.0
Denmark     1       0.0
Germany     1       0.0
Mexico      1       0.0

In [145]:
totals_by_country = data[columns_of_interest].groupby("country").sum()
totals_by_country.sort_values('sold', ascending=False)

         sold  mortgage
country
USA       177      61.0
Canada      7       0.0
Russia      4       1.0
Belgium     2       0.0
UK          2       0.0
Denmark     1       0.0
Germany     1       0.0
Mexico      1       0.0

In [146]:
# For the average computations, we use the following list of columns.
columns_of_interest = ['country', 'area', 'deal_satisfaction','price']

# We create a new variable where we will store the data relevant to our calculations.
averages_by_country = data[columns_of_interest].groupby("country").mean()
averages_by_country

                area  deal_satisfaction          price
country
Belgium   852.730000           3.000000  229075.470000
Canada    917.382857           5.000000  274069.384286
Denmark   785.480000           1.000000  257183.480000
Germany   743.410000           5.000000  205098.210000
Mexico   1283.450000           3.000000  338181.180000
Russia    903.757500           2.500000  278828.835000
UK        739.480000           4.000000  220142.680000
USA       900.794463           3.581921  270096.266554

In [147]:
# Frequency distribution by state
columns_of_interest = ['state', 'sold','mortgage']
totals_by_state = data[columns_of_interest].groupby("state").sum()
totals_by_state.sort_values('sold', ascending=False)

            sold  mortgage
state
California   120      41.0
Nevada        17       8.0
Arizona       11       3.0
Colorado      11       5.0
Oregon        11       1.0
Canada         7       0.0
Utah           5       1.0
Russia         4       1.0
Virginia       4       2.0
Belgium        1       0.0
Denmark        1       0.0
Kansas         1       0.0
Mexico         1       0.0
Wyoming        1       0.0

In [148]:
totals_by_state.sold.sum()

195

In [150]:
# To focus on the relative and cumulative frequency of sales, we can refine our table by state.
# We will start by excluding 'mortgage' from our columns of interest.
columns_of_interest = ['state', 'sold']

# We will store this data in a new variable called 'sold_by_state'.
sold_by_state = data[columns_of_interest].groupby("state").sum()
sold_by_state.sort_values('sold', ascending=False)

            sold
state
California   120
Nevada        17
Arizona       11
Colorado      11
Oregon        11
Canada         7
Utah           5
Russia         4
Virginia       4
Belgium        1
Denmark        1
Kansas         1
Mexico         1
Wyoming        1

In [151]:
# The term 'sold' may not be the best to describe frequency, so we can rename this column.
sold_by_state = sold_by_state.rename(columns={'sold':'frequency'})
sold_by_state

            frequency
state
Arizona            11
Belgium             1
California        120
Canada              7
Colorado           11
Denmark             1
Kansas              1
Mexico              1
Nevada             17
Oregon             11
Russia              4
Utah                5
Virginia            4
Wyoming             1

## Relative frequency distribution by state

In [153]:
# The relative frequency can be computed by dividing the frequency of each state by the total frequency.
sold_by_state['relative_frequency'] = sold_by_state['frequency']/sold_by_state['frequency'].sum()
sold_by_state.sort_values('frequency', ascending=False)

            frequency  relative_frequency
state
California        120            0.615385
Nevada             17            0.087179
Arizona            11            0.056410
Colorado           11            0.056410
Oregon             11            0.056410
Canada              7            0.035897
Utah                5            0.025641
Russia              4            0.020513
Virginia            4            0.020513
Belgium             1            0.005128
Denmark             1            0.005128
Kansas              1            0.005128
Mexico              1            0.005128
Wyoming             1            0.005128

In [155]:
# Calculate the cumulative sum of values on our relative frequency column.
sold_by_state['cumulative_frequency'] = sold_by_state['relative_frequency'].cumsum()
sold_by_state.sort_values('frequency', ascending=False)

            frequency  relative_frequency  cumulative_frequency
state
California        120            0.615385              0.676923
Nevada             17            0.087179              0.871795
Arizona            11            0.056410              0.056410
Colorado           11            0.056410              0.769231
Oregon             11            0.056410              0.928205
Canada              7            0.035897              0.712821
Utah                5            0.025641              0.974359
Russia              4            0.020513              0.948718
Virginia            4            0.020513              0.994872
Belgium             1            0.005128              0.061538
Denmark             1            0.005128              0.774359
Kansas              1            0.005128              0.779487
Mexico              1            0.005128              0.784615
Wyoming             1            0.005128              1.000000